### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by ocasti** [cdgco/vwi-ftp#1]
Hi, i implement the plugin and apache show memory exausted error:
1GB of memory for php and not work!.

PHP Fatal error:  Out of memory (allocated 991952896) (tried to allocate 262144 bytes)

**Comment by cdgco** [comment]
Hi, 

You can try increasing your memory limit in your php.ini file with the value:
`memory_limit = 32M`

or in a .htaccess file with the value:
`php_value memory_limit 32M`

I am unsure if this will fix the problem though, and I am unsure how much support I can offer as while I built the integration, the underlying software which is throwing this error is MostaFTP, not VWI or the plugin.
